name: ssh
on:
  watch:
    types: [started]
  push:
    tags:
    - 'v*'
    branches: 
      - master
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
       sudo apt-get update && sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib


    - name: Clone source code
      run: git clone https://github.com/coolsnowwolf/lede 

    - name: Update feeds
      run: cd lede && ./scripts/feeds update -a

    - name: Install feeds
      run: cd lede && ./scripts/feeds install -a

    - name: SSH connection to Actions
      uses: p3terx/debugger-action@master
 
    #- name: Upload bin directory
    #  uses: actions/upload-artifact@master
    #  with:
    #   name: OpenWrt_dl
    #    path: lede/dl
