name: ssh
on:
  watch:
    types: [started]
  push:
    tags:
    - 'v*'
    branches: 
      - master
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection to Actions
      uses: p3terx/debugger-action@master
 
    - name: Upload bin directory
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_dl
        path: lede/dl
